merged work and personal dots

diff --git a/dot_zprofile.tmpl b/dot_zprofile.tmpl
--- a/dot_zprofile.tmpl
+++ b/dot_zprofile.tmpl
@@ -1,6 +1,58 @@
+{{- if eq .machine.type "work" }}
+# sudo apt install gnome-keyring seahorse
+export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"
+# export SSH_ENV=$HOME/.ssh/environment_${HOSTNAME}
+#
+# function start_agent {
+#      echo -n "Initialising new SSH agent... "
+#      touch ${SSH_ENV}
+#      chmod 600 ${SSH_ENV}
+#      /usr/bin/ssh-agent -s | sed 's/^echo/#echo/' > ${SSH_ENV}
+#      echo "succeeded."
+#      . ${SSH_ENV} > /dev/null
+# }
+#
+# # Don't use Gnome keyring program (seahorse or whatever), because of GUI prompts.
+# if [[ $SSH_AUTH_SOCK =~ /run/user ]]; then
+#     unset SSH_AUTH_SOCK
+#     unset SSH_AGENT_PID
+# fi
+#
+# # Source SSH settings, if applicable
+# ssh-add -l > /dev/null 2>&1
+# if [ $? -eq 0 -o $? -eq 1 ]; then
+#     # echo "SSH Agent found."
+# else
+#     # echo -n "Looking for SSH Agent... "
+#     if [ -f "${SSH_ENV}" ]; then
+#         . ${SSH_ENV} > /dev/null
+#         ssh-add -l > /dev/null 2>&1
+#         if [ $? -eq 0 -o $? -eq 1 ]; then
+#             # echo "found pid: ${SSH_AGENT_PID}."
+#         else
+#             echo "SSH Agent not found."
+#             start_agent;
+#         fi
+#     else
+#         start_agent;
+#     fi
+#     ssh-add -l
+# fi
+{{- end}}
+
 export OMARCHY_PATH="$HOME/.local/share/omarchy"
 export PATH="$OMARCHY_PATH/bin:$PATH"
 export PATH="$HOME/.local/bin:$PATH"
 export PATH="$HOME/.cargo/bin:$PATH"
+
+{{- if eq .machine.type "work" }}
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+export GOPATH=$HOME/go
+export PATH=$HOME/bin:$PATH
+export PATH=$HOME/.opencode/bin:$PATH
+export PATH=$PATH:$GOPATH/bin
+{{- else }}
 export PATH="/home/jadon/.lmstudio/bin:$PATH"
-export PATH="/opt/rocm/bin:$PATH"
+{{- end}}
